; Stella Separation Awareness Firmware
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = stella

; --- Arduino Stella (nRF52840-based) target build ---
[env:stella]
platform = nordicnrf52
board = arduino_nano33ble
framework = arduino
lib_deps =
    arduino-libraries/ArduinoBLE@^1.3.6
build_flags =
    -DSTELLA_TARGET
    -Wall
    -Wextra

; --- Native desktop environment for TDD ---
[env:native]
platform = native
platform_packages = toolchain-gccmingw32
build_flags =
    -DNATIVE_TEST
    -std=c++14
    -Wall
    -Wextra
    -Itest/mocks
test_framework = unity
test_build_src = true
